name: Action

on: [push]

jobs:
  run_action:
    runs-on: ubuntu-latest
    name: Runs the action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Action step
        uses: ./
        with:
          style: docs/style.json
          center: [139.7671773, 35.6810755]
          zooms: [ 5, 7, 11, 14 ]
          production_style: https://geoloniamaps.github.io/basic/style.json
